name: Publish
on:
  pull_request:
    types: [closed]
    branches:
      - development
      - main

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 14'
        uses: actions/setup-node@v2
        with:
          node-version: '14.17.1'

      - name: 'Version and publish' # Interesting step
        env:
          GH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: lerna publish from-git
